version: "2"
services:
  api:
    build: backend/api
    ports:
      - "40042:5000"
  frontend:
    build: frontend
    ports:
      - "80:8080"
 mysql_db:
  image: mysql/mysql-server:latest
  environment: 
     - MYSQL_DATABASE=gdis_db
     - MYSQL_USER=gdis_db_user
     - MYSQL_PASSWORD=abcd1234
     - MYSQL_ROOT_PASSWORD=abcd1234
