version: "2"
services:
  redis:
    build: redis
    expose:
      - "6379"
  backend:
    build: backend
    links:
      - redis
    ports:
      - "81:81"
    tty: true
    environment:
      - GMAPS_KEY
  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - "80:8080"
    environment:
      - DNSNAME
