swagger: '2.0'
info:
  description: >-
    These APIs are used to interact with the Importer and to import, modify and
    delete tests to/from the database.
  version: 1.0.0
  title: Importer
  contact:
    email: placeholder@rwth-aachen.de
  license:
    name: GNU GPL v3
    url: 'https://www.gnu.org/licenses/gpl.txt'
host: localhost
basePath: /v2
tags:
  - name: importer
    description: Operations that the Importer provide
schemes:
  - http
paths:
  /importer/i/test-case:
    post:
      tags:
        - importer
      summary: Import a new test to the database
      description: Import a new test to the database
      operationId: handleImportRequest
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: >-
            The new test with all of its test data that has to be saved in the
            database
          required: true
          schema:
            $ref: '#/definitions/JSONWrapper'
      responses:
        '200':
          description: Test successfully imported
        '400':
          description: Test data is corrupted or incomplete
        '409':
          description: A test with the same name already exists
        '500':
          description: Internal server error. Can't connect to the database or similar
  '/importer/u/test-case/{id}':
    put:
      tags:
        - importer
      summary: Update a test case in the database
      operationId: handleUpdateRequest
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: The updated test with all of its updated test data
          required: true
          schema:
            $ref: '#/definitions/JSONWrapper'
        - name: id
          in: path
          description: The ID of the test which has to be updated
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Test successfully updated
        '400':
          description: >-
            Updated Test Data is null. Should not be returned, since the test
            data is checked before it is send to the database
        '404':
          description: A Test with this id doesn't exist
        '409':
          description: A Test with this updated name already exists
  '/importer/d/test-case/{storyType}/{id}':
    delete:
      tags:
        - importer
      summary: Delete a the test case with the given ID from the database
      operationId: handleDeleteRequest
      parameters:
        - name: storyType
          in: path
          description: The storyType of the test which has to be delete
          required: true
          type: string
        - name: id
          in: path
          description: The ID of the test which has to be delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Test successfully deleted
        '404':
          description: A Test with this id doesn't exist
definitions:
  JSONWrapper:
    type: object
    properties:
      testName:
        type: string
        description: The name under which the test will be saved in the database
      storyType:
        type: string
        description: The storyType (only basicStoryType currenly) of the new test
      storyName:
        type: string
        description: The storyName of the new test
      testData:
        type: array
        description: >-
          The actual test data. The data actually represents the rows of the
          tables from the Front End.
